CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE admin (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pelanggan (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    telepon VARCHAR(20),
    alamat TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE kategori (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_kategori VARCHAR(100) NOT NULL UNIQUE,
    deskripsi TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE alat_musik (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kategori_id INT REFERENCES kategori(id) ON DELETE SET NULL,
    nama_alat VARCHAR(150) NOT NULL,
    deskripsi TEXT,
    harga DECIMAL(12, 2) NOT NULL CHECK (harga > 0),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stok (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alat_id INT NOT NULL UNIQUE REFERENCES alat_musik(id) ON DELETE CASCADE,
    admin_id INT REFERENCES admin(id) ON DELETE SET NULL,
    jumlah INT NOT NULL DEFAULT 0 CHECK (jumlah >= 0),
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pembelian (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pelanggan_id INT NOT NULL REFERENCES pelanggan(id),
    status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'diproses', 'dikirim', 'selesai', 'dibatalkan')),
    total DECIMAL(14, 2) NOT NULL DEFAULT 0 CHECK (total >= 0),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE detail_pembelian (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pembelian_id INT NOT NULL REFERENCES pembelian(id) ON DELETE CASCADE,
    alat_id INT NOT NULL REFERENCES alat_musik(id),
    jumlah INT NOT NULL CHECK (jumlah > 0),
    harga_satuan DECIMAL(12, 2) NOT NULL,
    subtotal DECIMAL(14, 2) NOT NULL,
    UNIQUE (pembelian_id, alat_id)
);

CREATE TABLE log_aktivitas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sumber_event VARCHAR(50) NOT NULL,
    keterangan TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_alat_kategori ON alat_musik USING btree (kategori_id);
CREATE INDEX idx_pembelian_pelanggan ON pembelian USING btree (pelanggan_id);
CREATE INDEX idx_pembelian_status_tanggal ON pembelian USING btree (status, created_at);
CREATE INDEX idx_detail_pembelian_alat ON detail_pembelian USING btree (alat_id);
